### PR TITLE
Embed spoilers implementation

### PR DESCRIPTION
**Pull request by Skythrew**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects
* [x] I have included screenshots to demonstrate my changes

Just a simple pull request to add the frontend implementation for embed spoilers. I'll probably do the backend soon.

### CODE REVIEW

**Comment by Skythrew** [comment]
I updated my files to add the support of spoiler removing on click

**Comment by Skythrew** [comment]
The type check is currently failing because of the backend which is not implementing the spoiler property of the embed object

**Comment by Rexogamer** [comment]
We're also currently dealing with some dep issues that are failing a lot of PRs

**Review by khyrthy — APPROVED** [review]
It's all good! I'm approving it!

**Pull request closed without merging**
