### PR TITLE
Show errors for invalid length/username taken

### PR DESCRIPTION
**Pull request by ThatTonybo**
Modifies the bots pane in settings to show an error popup for length (if < 2, if > 32) and if the chosen username is taken. This imports the showScreen method (found in the FileUploader file). This pull depends on [a change to the revolt.js library](https://github.com/revoltchat/revolt.js/pull/6) I have already submitted (and linked), which catches and throws any errors from the bots.create method.

### CODE REVIEW

**Comment by insertish** [comment]
Now conflicts with #159.

**Comment by Rexogamer** [comment]
This needs to be added in `/popovers/CreateBot.tsx`.

**Comment by Rexogamer** [comment]
Just checking in - are you still willing to work on this?

**Comment by Rexogamer** [comment]
Closing due to inactivity - if you're still willing to work on this, feel free to reopen this/a new PR. Thanks!

**Pull request closed without merging**
