### PR TITLE
Center BotBadge text

### PR DESCRIPTION
**Pull request by frasurebuilds**
From
image
to
image

### CODE REVIEW

**Review by Mysterious-Dev — DISMISSED** [review]

**Review by Rexogamer — CHANGES_REQUESTED** [review]
Is this necessary? The text seems to be working fine as-is on my end:
image

**Comment by janderedev** [comment]
Checked in Firefox, Chromium (Brave) and Opera, it's centered on all of them for me. What browser are you using?

**Comment by seanfrasure** [comment]
> Checked in Firefox, Chromium (Brave) and Opera, it's centered on all of them for me. What browser are you using?

I'm using Brave. I tried it on 2 different devices with Brave and it still looks off-center.

**Comment by insertish** [comment]
I'm not sure if by fixing it for one browser it'll break it for another, maybe this should just be an inline grid or flex? Which then positions the child in the center.

**Comment by seanfrasure** [comment]
image

`inline-grid` works but it misaligns the text, though you can fix this with some position adjustments (e.i. parent, relative; child, absolute) to produce this:

image

**Pull request closed without merging**
