### PR TITLE
fix(home): inconsistent discover button height

### PR DESCRIPTION
**Pull request by ashley0143**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects
* [ ] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
* [x] I have included screenshots to demonstrate my changes

this pr fixes inconsonant height in the buttons by making all of them the same size :3
before:
image

after:
image

### CODE REVIEW

**Comment by DiamondBuff** [comment]
I approve of this

**Comment by stationaryStation** [comment]
This should not be an issue on the new client. And I don't think it will get accepted, given that Alan made a pull request for the bot invite screen, and it got denied due to the client rewrite, if I recall/understood correctly.

But we'll see what the others think about it :3

**Comment by ashley0143** [comment]
so weird - its just a css commit aa

**Comment by aox2** [comment]
W

**Comment by ktwrd** [comment]
> so weird - its just a css commit aa



> Update: the build failure is unrelated to this PR - approving

failing because of [external/components](https://github.com/revoltchat/components)

**Comment by ashley0143** [comment]
why is it failng?

**Comment by Rexogamer** [comment]
The components submodule, which is unrelated to your changes

**Review by ArnavK-09 — APPROVED** [review]

**Pull request merged**
