### PR TITLE
feat(ServerSettings.Roles): Allow to copy role ID

### PR DESCRIPTION
**Pull request by mafineeek**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [ ] These changes do not have any notable side effects on other Revolt projects
* [x] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
* [x] I have included screenshots to demonstrate my changes

https://i.imgur.com/Najhfey.png

### CODE REVIEW

**Comment by mafineeek** [comment]
https://github.com/revoltchat/translations/pull/27 Needs to be merged too.

**Comment by Rexogamer** [comment]
Due to the soon:tm:-to-be-released backend rewrite and its changes to how permissions work, the role settings page may need to be redone (meaning this PR would nead to be redone/may become obsolete)

**Comment by insertish** [comment]
I believe this page was rewritten on [quark/permissions](https://github.com/revoltchat/revite/tree/quark/permissions), and is due further work before that branch is merged in.

**Comment by insertish** [comment]
It is now indeed conflicting

**Comment by Rexogamer** [comment]
?

**Pull request closed without merging**
