### PR TITLE
fix: display server identity (if present) in typing indicator

### LINKED ISSUE #64: Server nickname / pfp overrides don't reflect in the typing indicator

### PR DESCRIPTION
**Pull request by LedaThemis**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects
* [ ] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
* [x] I have included screenshots to demonstrate my changes

Fixes #64 

Before:
before image

After:
after image
if there's no server identity(nickname or avatar) set, it uses user's global name and avatar.

### CODE REVIEW

**Comment by Rexogamer** [comment]
I think one of the blockers for this in the past was a possible memory leak - is memory usage stable after this patch?

**Comment by LedaThemis** [comment]
Memory usage looks stable,
#### 1 Iteration
aa9974149cb4cd86ee9b53b2582cb116bc5cc1c3: `8.117MB` to `8.162MB` (0.045MB), 7.980MB (-0.182MB) after garbage collection. (nightly)

7f5a7aec8689c329fa970e1eecddba7c3ccfa398: `8.050MB` to `8.095MB` (0.045MB), 7.967MB (-0.128MB) after garbage collection.

**Comment by insertish** [comment]
I  think the issue previously  was with TextReact and I think I implemented a memory leak in there or something, this looks  fine though.

**Comment by insertish** [comment]
Had to revert, I was merging PRs quite quickly so I missed this issue entirely: this does not consider situations where member objects are not available (may not have synced) or if we're in a DM (no server).

**Pull request merged**
