### PR TITLE
Add text size option to appearance settings

### PR DESCRIPTION
**Pull request by shadyalfred**
Add an input tag in Appearance settings page that edits global `--text-size` variable

### CODE REVIEW

**Comment by insertish** [comment]
Few issues:
- The text size is added but not used.
- I'm currently trying to avoid editing settings menus since I'm going to start work on #137 soon.
- This would probably be better as a slider.

**Comment by ShaadiAlfred** [comment]
I think it would be better then to postpone adding an option to change the text size till the MobX branch gets merged.

Is there a slider component in the code base that I can use or would I have to create my own?

I'm not sure what do you mean by `text size is added but not used`. Do you mean this 
image
?
If yes, I added it to follow the commented line above, I thought it was required as a reference or something.

**Comment by Rexogamer** [comment]
The MobX migration has now completed, so feel free to resume your work here

**Comment by trashtemp** [comment]
We should consider splitting text sizing into two variables:

`--chat-text-size`: font size for the chat area
`--text-size`: font size for the rest of the app

That way users could increase or decrease either one of these values without affecting the other. Some might prefer to have larger text only in the chat area, while some might prefer to increase both values.

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Pull request closed without merging**
