### PR TITLE
Use CSS to calculate the aspect ratio and sizing [Needs testing]

### PR DESCRIPTION
**Pull request by brecert**
This needs testing

### CODE REVIEW

**Comment by insertish** [comment]
Stuff likes to become very tall on Firefox 92.
Message Link: https://revoltchat.github.io/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01FDAY86R8XYHRXDK5H707GC87/01FFZCMFKKW45KYYDQ5NH8TSXC

image

**Comment by insertish** [comment]
image

Video component appears to be escaping.

image

**Comment by brecert** [comment]
> Video component appears to be escaping.

Can you provide more details? I'm having trouble reproducing on Firefox.

**Comment by brecert** [comment]
This isn't the right solution to the CSS problem.

**Pull request closed without merging**
