### PR TITLE
feat: require at least two characters to autocomplete emoji

### PR DESCRIPTION
**Pull request by brecert**
- why? it makes typing `:3` easier

### CODE REVIEW

**Comment by RigidStudios** [comment]
Some people may not remember the full name and are just guessing it, it would be a hindrance to not have direct autocomplete.

**Comment by brecert** [comment]
> Some people may not remember the full name and are just guessing it, it would be a hindrance to not have direct autocomplete.

Do you have any ideas on how `:3` and similar could be typed easier while still allowing for guessing based on a single character?

**Comment by RigidStudios** [comment]
> > Some people may not remember the full name and are just guessing it, it would be a hindrance to not have direct autocomplete.
> 
> Do you have any ideas on how `:3` and similar could be typed easier while still allowing for guessing based on a single character?

I would propose the addition of escape serving as escaping emoji autocomplete and return override.

**Comment by brecert** [comment]
> > > Some people may not remember the full name and are just guessing it, it would be a hindrance to not have direct autocomplete.
> > 
> > 
> > Do you have any ideas on how `:3` and similar could be typed easier while still allowing for guessing based on a single character?
> 
> I would propose the addition of escape serving as escaping emoji autocomplete and return override.

This makes sense, what about mobile?

**Comment by RigidStudios** [comment]
> > > > Some people may not remember the full name and are just guessing it, it would be a hindrance to not have direct autocomplete.
> > > 
> > > 
> > > Do you have any ideas on how `:3` and similar could be typed easier while still allowing for guessing based on a single character?
> > 
> > 
> > I would propose the addition of escape serving as escaping emoji autocomplete and return override.
> 
> This makes sense, what about mobile?

I'm not a mobile user, but can you not simply press a send button to send your message? Shouldn't emojis only be triggered by tapping on them?

**Comment by brecert** [comment]
> but can you not simply press a send button to send your message

Ah yeah, I forgot about that.
My bad.

> Shouldn't emojis only be triggered by tapping on them?

Hitting enter still selects them on mobile as well.

Part of the reason I'm discussing this is because I was planning to add a requirement for 2 or more on other types of auto-completions in the future as well. https://github.com/revoltchat/revite/issues/249#issuecomment-920263643

**Comment by RigidStudios** [comment]
> Hitting enter still selects them on mobile as well.

Hm, that should be fixed.

I don't think the @ is a problem either, we'll see what others think though.

**Review by insertish — APPROVED** [review]

**Comment by insertish** [comment]
I'm for this change and see no issue with merging, Discord does it this way as well.

**Pull request merged**
