### PR TITLE
add richtext improvements for markdown renderer

### PR DESCRIPTION
**Pull request by bdbch**
Currently markdown rendering looks broken (see old screenshot):

image

I added margins to the specific elements that were missing spacings completely to make it look like this:

image

### CODE REVIEW

**Comment by insertish** [comment]
I'd agree on adding margins (although not as much as in picture) to list items but probably not the headings, too much wasted white space imo.

**Comment by bdbch** [comment]
What would be your suggestion since headlines should also be grouped together with the content it describes by law of proximity?
https://lawsofux.com/law-of-proximity/

**Comment by bdbch** [comment]
First thing I could reduce is the bottom margin on headlines to remove some of the white space but I'd still keep a clean separation to the content above (if there is any content obv.)

**Comment by Rexogamer** [comment]
Any progress on this? (I agree that reducing the spacing slightly would be a good idea.)

**Comment by bdbch** [comment]
I removed the margin on headlines and tweaked blockquotes in combination with paragraphs.

image

**Review by Rexogamer — APPROVED** [review]

**Comment by Rexogamer** [comment]
We've just switched from markdown-it to remark, so this will probably need to be re-implenented

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.

**Pull request closed without merging**
