### PR TITLE
Add "All other sessions" logout confirmation modal

### PR DESCRIPTION
**Pull request by 3nt3**
This adds a prompt when the users tries to log out of all other sessions as proposed in #42.

Screenshot

I made translations for English and German but more will be needed.

### CODE REVIEW

**Comment by insertish** [comment]
This is a pretty long string, does it behave on mobile?
I'd prefer to have the second sentence as content.

Also conflicting.

**Comment by 3nt3** [comment]
@insertish 

> This is a pretty long string, does it behave on mobile?

I see that, will work on it

> Also conflicting.

My IDE must have removed a `?` automatically. I will resolve that

**Comment by 3nt3** [comment]
> This is a pretty long string, does it behave on mobile?

Fixed it 2021-11-01_861x1592

**Comment by Rexogamer** [comment]
Is this ready for code review? Tested locally - seems to work fine.

**Comment by 3nt3** [comment]
this seems to be fixed and can be closed

**Pull request closed without merging**
