### PR TITLE
fix(messages): don't attempt to display revolt wiki link as invite

### PR DESCRIPTION
**Pull request by infi**
* [X] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [X] I have tested my changes locally and they are working as intended
* [X] These changes do not have any notable side effects on other Revolt projects
* [X] ~~(optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)~~
* [X] I have included screenshots to demonstrate my changes

## Current Behavior
image

## Expected Behavior Implemented by PR
image

### CODE REVIEW

**Review by Rexogamer — APPROVED** [review]

**Review by janderedev — APPROVED** [review]

**Review by janderedev — CHANGES_REQUESTED** [review]
Actually, isn't the negative lookbehind unsupported in safari? I broke revite with this once

https://caniuse.com/js-regexp-lookbehind

**Review by insertish — APPROVED** [review]

**Comment by insertish** [comment]
> Actually, isn't the negative lookbehind unsupported in safari? I broke revite with this once
> 
> [caniuse.com/js-regexp-lookbehind](https://caniuse.com/js-regexp-lookbehind)

Oh, can we check this first :trollface:

**Comment by Rexogamer** [comment]
Slightly hacky alternative to the lookbehind: make sure `http(s)://` appears directly before `rvlt.gg`

**Comment by insertish** [comment]
Closing due to rewrite, marking as potential issue in future by linking to https://github.com/revoltchat/frontend/issues/134.

**Pull request closed without merging**
