### PR TITLE
fix: dash ("-" char) in emoji names

### PR DESCRIPTION
**Pull request by ktwrd**
## Please make sure to check the following tasks before opening and submitting a PR

* [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [x] I have tested my changes locally and they are working as intended
* [x] These changes do not have any notable side effects on other Revolt projects
* [ ] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
* [x] I have included screenshots to demonstrate my changes

This fixes emoji names that have a `-` in them. For example, this fixes the usage of `:non-potable_water:` to show the emoji properly without avoiding this error by changing all emoji names to not have any `-`'s in them.

Along with fixing this bug, it also removed an unnecessary "one or more" operator in the same `RE_EMOJI` expression. This makes no difference to validating with the expression, except to readability.

before
image

after

### CODE REVIEW

**Review by janderedev — DISMISSED** [review]
i trust you that it works :trollface:

**Comment by ktwrd** [comment]
added screenshots

**Comment by ktwrd** [comment]
Along with fixing this bug, it also removed an unnecessary "one or more" operator in the same `RE_EMOJI` expression. This makes no difference to validating with the expression, except to readability.

**Review by janderedev — APPROVED** [review]

**Comment by Rexogamer** [comment]
A quick check with Regex101 indicates that this should work as expected ^^

**Review by Rexogamer — DISMISSED** [review]
A quick check with Regex101 indicates that this should work as expected ^^

**Comment by janderedev** [comment]
"You’re not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request." 🤓

**Comment by ktwrd** [comment]
bruh the checkout task fails 💀💀💀💀💀💀

**Comment by ktwrd** [comment]
Fixed the workflow failing, and nothing is broken!

**Comment by Rexogamer** [comment]
Looks like the CI error is back to where it was before (it was unable to link the submodules correctly)

**Comment by ktwrd** [comment]
Rebased to fix CI

**Review by janderedev — APPROVED** [review]

**Pull request merged**
