### PR TITLE
fix: limit size of external link prompt

### LINKED ISSUE #372: Opening long link
Popup when opening sketchy links need some improvements, this is what happen when opening a long link

Image: https://the-anime-god.is-inside.me/FujLUdLx.png

Suggestion: Maybe make it link when you open or delete like in discord? https://the-anime-god.is-inside.me/zhjW7YAH.png

### PR DESCRIPTION
**Pull request by janderedev**
fixes #372.

This probably breaks on mobile, will test later, hence draft PR.

### CODE REVIEW

**Comment by janderedev** [comment]
Should work fine on mobile devices now.

Also, can someone please fix the goddamn CI?

**Comment by insertish** [comment]
Can you rebase master on to this branch, will also fix CI.

**Comment by janderedev** [comment]
not quite what i intended to  do, but it seems to have worked i think

**Comment by insertish** [comment]
Superseded by #522

**Pull request closed without merging**
